common/models/Users.php
<?php
namespace common\models;

use common\components\traits\Validation;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\helpers\Url;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class Users extends ActiveRecord implements IdentityInterface
{
    use Validation;

    const STATUS_DELETED = 0;
    const STATUS_DEACTIVATED = 3;
    const STATUS_ACTIVE = 10;

    public static $Statuses = [
        self::STATUS_ACTIVE => "Активирован",
        self::STATUS_DEACTIVATED => "Деактивирован",
    ];

    const TYPE_ADMIN = 1;
    const TYPE_USER = 2;

    public $confirm_pass;
    public $surname;
    public $patronymic;
    public $phone;
    public $city;
    public $type;
    public $content;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%users}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new Expression('NOW()'),
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email','password_hash'], 'required'],
            [['status', 'email_confirmed', 'users_roles_id', 'type', 'city_people_id'], 'integer'],
            [['email'], 'unique'],
            [['email'], 'email'],
            [['name', 'password_hash', 'password_reset_token', 'email', 'surname', 'patronymic', 'phone', 'confirm_pass', 'city'], 'string', 'max' => 255],
            [['password_hash'], 'string', 'min' => 6],
            [['auth_key'], 'string', 'max' => 32],
            [['password_reset_token'], 'unique'],
            [['content'], 'safe'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['users_roles_id', 'default', 'value' => self::TYPE_USER],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED, self::STATUS_DEACTIVATED]],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'email' => 'E-mail',
            'created_at' => 'Дата регистрации',
            'updated_at' => 'Дата изменения',
            'password_hash' => 'Пароль',
            'confirm_pass' => 'Подтверждение пароля',
            'status' => 'Статус',
            'surname' => 'Фамилия',
            'patronymic' => 'Отчество',
            'city' => 'Город',
            'users_roles_id' => 'Роль',
            'phone' => 'Телефон',
            'type' => 'Форма организации',
            'city_people_id' => 'Население города',
        ];
    }

    public static function find()
    {
        return parent::find()->onCondition(static::tableName() . '.status <> :status OR ' . static::tableName() . '.status IS NULL',
            [
                ':status' => self::STATUS_DELETED
            ]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getUsersProfile()
    {
        return $this->hasOne(UsersProfile::className(), ['users_id' => 'id']);
    }

    public function getUsersRoles()
    {
        return $this->hasOne(UsersRoles::className(), ['id' => 'users_roles_id']);
    }

    public function getCityPeople()
    {
        return $this->hasOne(CityPeople::className(), ['id' => 'city_people_id']);
    }

    public static function deleteUser($id){
        $model = Users::findOne($id);
        if(!empty($model)){
            $model->email = $model->email.'.'.time();
            $model->status = Users::STATUS_DELETED;
            if($model->save()){
                return true;
            } else {
                return false;
            }
        }else {
            return false;
        }

    }

    public function getArrayField(){
        return array('content');
    }

    public static function testprofile(){
        $user = Users::findOne(['id' => Yii::$app->user->id]);
        if(empty($user->city_people_id)){
            return false;
        }else {
            return true;
        }
    }
}

frontend/views/layouts/main/footer.php
<footer class="footer text-center">© <?=date('Y')?>. Все права защищены.</footer>

frontend/views/layouts/main/header.php
<!-- ============================================================== -->
<!-- Preloader -->
<!-- ============================================================== -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
    </svg>
</div>
<!-- ============================================================== -->
<!-- Wrapper -->
<!-- ============================================================== -->
<div id="wrapper">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <nav class="navbar navbar-default navbar-static-top m-b-0">
        <div class="navbar-header">
            <div class="top-left-part">
                <!-- Logo -->
                <a class="logo" href="index.html">
                    <span class="hidden-sm hidden-md hidden-lg">
                    </span>
                    <span class="hidden-xs">
                    </span>
                </a>
            </div>
            <!-- /Logo -->
            <ul class="nav navbar-top-links navbar-left">
                <li><a href="javascript:void(0)" class="open-close waves-effect waves-light visible-xs"><i class="ti-close ti-menu"></i></a></li>
            </ul>
            <ul class="nav navbar-top-links navbar-right pull-right">
                <li class="dropdown">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#"> <img src="/plugins/images/users/varun.jpg" alt="user-img" width="36" class="img-circle hidden"><b class="hidden-xs"><?=Yii::$app->user->identity->name?> <?=Yii::$app->user->identity->usersProfile->surname?></b><span class="caret"></span> </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <div class="dw-user-box p-b-5">
                                <div class="u-text">
                                    <h4><?=Yii::$app->user->identity->name?> <?=Yii::$app->user->identity->usersProfile->surname?></h4>
                                    <p class="text-muted">Ваш ID: <?=Yii::$app->user->identity->id?></p>
                                </div>
                            </div>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="<?=\yii\helpers\Url::to(['/auth/users/logout'])?>"><i class="fa fa-sign-out"></i>&nbsp; Выйти</a></li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>

                <!-- /.dropdown -->
            </ul>
        </div>
        <!-- /.navbar-header -->
        <!-- /.navbar-top-links -->
        <!-- /.navbar-static-side -->
    </nav>

    <!-- End Top Navigation -->

frontend/views/layouts/main/navigation.php
<?
use \yii\helpers\Url;
?>
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->

<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav slimscrollsidebar">
        <div class="sidebar-head">
            <h3><span class="fa-fw open-close"><i class="ti-menu hidden-xs"></i><i class="ti-close visible-xs"></i></span> <span class="hide-menu">Навигация</span></h3> </div>
        <ul class="nav" id="side-menu">
            <li> <a href="<?=Url::to(['/site/index'])?>" class="waves-effect"><i class="mdi mdi-gauge fa-fw"></i><span class="hide-menu">Главная панель</span></a></li>
            <li><a href="<?=Url::to(['/finance/finance/index'])?>" class="waves-effect"><i class="mdi mdi-currency-rub fa-fw"></i><span class="hide-menu">Финансы</span></a></li>
            <li><a href="<?=Url::to(['/royalty/royalty/index'])?>" class="waves-effect"><i class="mdi mdi-plus fa-fw"></i><span class="hide-menu">Расчет роялти</span></a></li>
            <li><a href="<?=Url::to(['/income/income/index'])?>" class="waves-effect"><i class="mdi mdi-clipboard-flow  fa-fw"></i><span class="hide-menu"> Доход/Расход</span></a> </li>
            <li><a href="<?=Url::to(['/planning/planning/index'])?>" class="waves-effect"><i class="mdi mdi-chart-pie  fa-fw"></i><span class="hide-menu"> Фин. планирование</span></a> </li>
            <li><a href="<?=Url::to(['/users/users/profile'])?>" class="waves-effect"><i class="mdi mdi-face  fa-fw"></i><span class="hide-menu"> Профиль</span></a> </li>
            <li><a href="<?=Url::to(['/auth/users/logout'])?>" class="waves-effect"><i class="mdi mdi-logout fa-fw"></i> <span class="hide-menu">Выйти</span></a></li>
        </ul>
    </div>
</div>
<!-- ============================================================== -->
<!-- End Left Sidebar -->
<!-- ============================================================== -->